version: '3.1'
services:
    postgres:
        build: images/postgres
        environment: 
            POSTGRES_PASSWORD: "*6Z,<[9A97Mp;6W"
        ports: 
            - 5432:5432
        volumes: 
            - ./data/postgres:/var/lib/postgresql/data

    adminer:
        image: adminer
        restart: always
        ports:
        - 8082:8080

    redis:
        build: images/redis
        ports:
            - 6379:6379
        volumes: 
            - ./data/redis:/data
    
    mongo:
        image: mongo
        volumes: 
            - ./data/mongo:/data/db
            - ./images/mongo/init.d:/docker-entrypoint-initdb.d
        environment: 
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: "iCOVXGj7WqlH4Z"
            MONGO_INITDB_DATABASE: criminalquery
        ports: 
            - 27017:27017

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: "iCOVXGj7WqlH4Z"

    # nginx:
    #     image: nginx
    #     volumes:
    #         - ./data/nginx:/usr/share/nginx/html:ro
    #         - ./images/nginx/criminal.conf:/etc/nginx/conf.d/criminal.conf
    #         - ./images/nginx/ssl:/etc/nginx/ssl
    #     ports:
    #         - "80:80"
    #     environment:
    #         - NGINX_HOST=criminal.local
    #         - NGINX_PORT=80
