version: '3.1'
services:
    postgres:
        build: images/postgres
        environment: 
            POSTGRES_PASSWORD: "*6Z,<[9A97Mp;6W"
        ports: 
            - 5432:5432
        volumes: 
            - ./data/postgres:/var/lib/postgresql/data

    adminer:
        image: adminer
        restart: always
        ports:
        - 8080:8080

    redis:
        build: images/redis
        ports:
            - 6379:6379
        volumes: 
            - ./data/redis:/data