server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: "*6Z,<[9A97Mp;6W"
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
  redis:
    host: redis
    port: 6379
    password: "PC.c&Qv9z.B1Y8K"
  data:
    mongodb:
      uri: mongodb://root:iCOVXGj7WqlH4Z@localhost/admin
  servlet:
    multipart:
      location: "/tmp"
      max-file-size: 20MB

mybatis:
  mapper-locations:
    - classpath*:mapper/*Mapper.xml
  config-location:
    - "classpath*:mybatis-config.xml"

oss:
  bucketName: "criminalquery"
  endPoint: oss-cn-beijing.aliyuncs.com
  accessKeyID: LTAI0vy29K3Sx81Y
  accessKeySecret: SMd3a4DFkwCtQbOOOj9WV300bm6VEz
