server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: "*6Z,<[9A97Mp;6W"
    driver-class-name: org.postgresql.Driver
  redis:
    host: redis
    port: 6379
    password: "PC.c&Qv9z.B1Y8K"
  data:
    mongodb:
      uri: mongodb://root:iCOVXGj7WqlH4Z@localhost/admin

mybatis:
  mapper-locations:
    - classpath*:mapper/*Mapper.xml
  config-location:
    - "classpath*:mybatis-config.xml"

logging:
  file:

criminal:
  cos:
    appid: "asdlkfjlkw3jr2kl3"

